spring:
  datasource:
    url: jdbc:h2:mem:denuncias;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: jose
    password: '91745'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: jose
      password: '91745'
      roles: CIDADAO
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: info


